import 'package:cloud_firestore/cloud_firestore.dart';

import '../../../../core/constants/api_endpoints.dart';
import '../../../../core/error/exceptions.dart';
import '../../domain/entities/instrument_category.dart';
import '../../domain/repositories/courses_repository.dart';
import '../models/course_model.dart';
import '../models/course_section_model.dart';
import '../models/lecture_model.dart';

abstract interface class CoursesRemoteDataSource {
  Future<CoursesPageDto> fetchCourses({
    InstrumentCategory? category,
    CourseLevel? level,
    String? cursor,
    required int limit,
  });

  Future<CourseModel> fetchCourseById(String id);
  Future<List<CourseModel>> fetchFeatured({required int limit});

  Future<List<CourseSectionModel>> fetchSections(String courseId);
}

class CoursesPageDto {
  CoursesPageDto({
    required this.items,
    required this.nextCursor,
    required this.hasMore,
  });
  final List<CourseModel> items;
  final String? nextCursor;
  final bool hasMore;
}

class CoursesRemoteDataSourceImpl implements CoursesRemoteDataSource {
  CoursesRemoteDataSourceImpl({required FirebaseFirestore firestore})
      : _firestore = firestore;

  final FirebaseFirestore _firestore;

  CollectionReference<Map<String, dynamic>> get _courses =>
      _firestore.collection(FirestoreCollections.courses);

  @override
  Future<CoursesPageDto> fetchCourses({
    InstrumentCategory? category,
    CourseLevel? level,
    String? cursor,
    required int limit,
  }) async {
    Query<Map<String, dynamic>> q = _courses;

    if (category != null) q = q.where('category', isEqualTo: category.id);
    if (level != null) q = q.where('level', isEqualTo: level.id);

    q = q.orderBy('publishedAt', descending: true).limit(limit + 1);

    if (cursor != null) {
      final cursorDoc = await _courses.doc(cursor).get();
      if (cursorDoc.exists) q = q.startAfterDocument(cursorDoc);
    }

    try {
      final snap = await q.get();
      final docs = snap.docs;
      final hasMore = docs.length > limit;
      final pageDocs = hasMore ? docs.sublist(0, limit) : docs;

      return CoursesPageDto(
        items: pageDocs.map(CourseModel.fromDoc).toList(),
        nextCursor: hasMore ? pageDocs.last.id : null,
        hasMore: hasMore,
      );
    } on FirebaseException catch (e) {
      throw ServerException(
        message: e.message ?? 'Failed to load courses.',
        statusCode: 0,
      );
    }
  }

  @override
  Future<CourseModel> fetchCourseById(String id) async {
    try {
      final doc = await _courses.doc(id).get();
      if (!doc.exists) {
        throw ServerException(message: 'Course not found.', statusCode: 404);
      }
      return CourseModel.fromDoc(doc);
    } on FirebaseException catch (e) {
      throw ServerException(message: e.message ?? 'Fetch failed.');
    }
  }

  @override
  Future<List<CourseModel>> fetchFeatured({required int limit}) async {
    try {
      final snap = await _courses
          .where('isFeatured', isEqualTo: true)
          .orderBy('publishedAt', descending: true)
          .limit(limit)
          .get();
      return snap.docs.map(CourseModel.fromDoc).toList();
    } on FirebaseException catch (e) {
      throw ServerException(message: e.message ?? 'Fetch failed.');
    }
  }

  @override
  Future<List<CourseSectionModel>> fetchSections(String courseId) async {
    try {
      // 1. Read section docs in order.
      final sectionsRef = _courses
          .doc(courseId)
          .collection(FirestoreCollections.sections);
      final sectionsSnap = await sectionsRef.orderBy('order').get();

      // 2. For each section, fetch its lectures subcollection in parallel.
      //    The admin portal writes lectures as docs at
      //      courses/{cid}/sections/{sid}/lectures/{lid}
      //    so we hydrate the embedded `lectures` field on each
      //    CourseSectionModel from that subcollection rather than the
      //    section doc itself (the section doc does NOT carry an
      //    embedded `lectures` array).
      final lectureLists = await Future.wait(
        sectionsSnap.docs.map((sectionDoc) async {
          final lecSnap = await sectionsRef
              .doc(sectionDoc.id)
              .collection(FirestoreCollections.lectures)
              .orderBy('order')
              .get();
          return lecSnap.docs.map((d) {
            final data = d.data();
            return LectureModel.fromJson({...data, 'id': d.id});
          }).toList();
        }),
      );

      // 3. Stitch the two together. Reuse CourseSectionModel.fromDoc to
      //    map the top-level section fields, then copyWith the lectures
      //    list in. copyWith is generated by freezed.
      return List<CourseSectionModel>.generate(
        sectionsSnap.docs.length,
        (i) {
          final base = CourseSectionModel.fromDoc(sectionsSnap.docs[i]);
          return base.copyWith(lectures: lectureLists[i]);
        },
      );
    } on FirebaseException catch (e) {
      throw ServerException(
        message: e.message ?? 'Failed to load curriculum.',
      );
    }
  }
}
